In [1]:
import numpy as np

In [8]:
# 2 by 2 matrices
w1  = np.array([[1, 2], [3, 4]])
w2  = np.array([[5, 6], [7, 8]])
print(w1)
print(w2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [9]:
# flatten
w1_flat = np.reshape(w1, -1)
w2_flat = np.reshape(w2, -1)
print(w1_flat)
print(w2_flat)

[1 2 3 4]
[5 6 7 8]


In [5]:
w = np.concatenate((w1_flat, w2_flat))
w

array([1, 2, 3, 4, 5, 6, 7, 8])