In [4]:
import numpy as np
import pandas as pd

In [5]:
features = np.array([ 0.49671415, -0.1382643 ,  0.64768854])
print(features)

[ 0.49671415 -0.1382643   0.64768854]


In [7]:
#in numpy for a 1D array, the transpose will return a row vector
features.T

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [8]:
#use arr[:,None] instead
features[:, None]

array([[ 0.49671415],
       [-0.1382643 ],
       [ 0.64768854]])

In [10]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_in_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_out = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_in_hidden)
hidden_layer_out = np.dot(hidden_layer_in, weights_hidden_out)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = sigmoid(np.dot(X, weights_in_hidden))
output_layer_out = sigmoid(np.dot(output_layer_in, hidden_layer_in))

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[ 0.0620095   0.03126734]
Output-layer Output:
0.433135520642


In [14]:
output_layer_in

array([ 0.41492192,  0.42604313,  0.5002434 ])

In [15]:
output_layer_out

0.43313552064216709